### PR TITLE
feat(product creation): add controller for seller product creation

### PR DESCRIPTION
**Pull request by robsdagreat**
What does this PR do?
Have logged in seller be able to create a product

Description of Task to be completed?
Have check if the user creating the product is a seller
Have check if the body for product is validated
Have check if that particular product is not in the seller's stock
Have seller be able to create a product successfully upon all the checks passed 

How should this be manually tested?
After clonning the repo, Run yarn run devstart to start the server, then use postman with the appropriate route
ex: "http://localhost:3000/api/product/create"

What are the relevant pivotal tracker stories
#187570874

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
Good Job Robert but please:
- [x] Make sure you add authorization to your endpoint we need to check if a logged in user is the one creating a product not just if he/she is a seller
- [x] Fix conflicts

**Review by kirengamartial — APPROVED** [review]
the code looks and no conflicts

**Review by Balinda21 — APPROVED** [review]
Great work

**Review by Ishimwe7 — APPROVED** [review]
Good job @robsdagreat , everything is clear

**Review by DeliceLydia — APPROVED** [review]
Good Job Robert

**Pull request merged**
