### PR TITLE
added users  logout functionality and redis for session management

### PR DESCRIPTION
**Pull request by Ishimwe7**
### What does this PR do?
This PR adds a logout functionality to the application, allowing users to log out by deleting their authentication token from redis.
### Description of Task to be completed?
1. Extract the authentication token from the request header.
2. Check if the token exists.
3. Delete the token from the server.
4. Return an appropriate response based on whether the token was successfully deleted.
### How should this be manually tested?
1. Start the server
2. Use a tool like Postman to send a POST request to the logout endpoint.
3. Set the Authorization header with the token, e.g., Authorization: Bearer <token>.

### CODE REVIEW

**Review by robsdagreat — APPROVED** [review]
Well go buddy! nice work

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
- Pacifique I suggest that after logging out a user you should not accept to logout again and again after a user is already logged out you should display another message `You already logged out` or `You are not logged in`

**Review by DeliceLydia — COMMENTED** [review]
Screenshot 2024-05-21 at 14 57 06
I am getting this `bad request` even when i log out for the first time

**Comment by Ishimwe7** [comment]
Let me recheck again

**Review by DeliceLydia — APPROVED** [review]

**Pull request merged**
