### PR TITLE
added .env.example

### PR DESCRIPTION
**Pull request by Balinda21**
### What does this PR do?
This PR add .env.example

### CODE REVIEW

**Review by bahati10 — APPROVED** [review]
Thanks for adding env.example file 
this file is important to our project

**Review by kirengamartial — APPROVED** [review]
this file is important too to know env variables used

**Review by derrick-nuby — CHANGES_REQUESTED** [review]
the .env file should never be published even if its details are not there one might brute force the application, so it is a security concern

**Comment by kirengamartial** [comment]
> the .env file should never be published even if its details are not there one might brute force the application, so it is a security concern

no  .env.example reserved for showing anyone who what's to clone our application what env variables he will need there are no sensitive data inside

**Comment by derrick-nuby** [comment]
> > the .env file should never be published even if its details are not there one might brute force the application, so it is a security concern
> 
> no  .env.example reserved for showing anyone who what's to clone our application what env variables he will need there are no sensitive data inside

Ahh okay, then that is fine no problem

**Review by derrick-nuby — APPROVED** [review]
If this is an example they can go ahead and merge this pr and it looks good for me.

**Pull request merged**
