### PR TITLE
config circle ci docker deploying

### PR DESCRIPTION
**Pull request by rodriguecyber**
### What does this PR do?
1. Update circleci for 
- build server
-  deploy docker image

### Description of Task to be completed?

- Deploying service to render using docker image

### How should this be manually test

- Push your changes to gytour branch 
- Test will be automatically  run  by circleci
- check circleci test result

### CODE REVIEW

**Review by kirengamartial — APPROVED** [review]
your circle ci good looks and read for merge and continuous deployment is configured well

**Review by bahati10 — APPROVED** [review]
Your changes look good and now Continuous deployment can happen.

**Review by robsdagreat — APPROVED** [review]
I see you finally did it and handle the environment variables issue on CircleCi. Well done @rodriguecyber !

**Review by Ishimwe7 — APPROVED** [review]
good job Rodrigue

**Pull request merged**
