### PR TITLE
Modify production details cors policy

### PR DESCRIPTION
**Pull request by rodriguecyber**
### What does this PR do?
- modify Cors policy 
- remove unused routes
- add swagger documentation to update password and update user routes

### CODE REVIEW

**Review by Balinda21 — APPROVED** [review]
You have issues on circleci address them, 
Otherwise Great work @rodriguecyber we needed this!

**Review by robsdagreat — APPROVED** [review]

**Comment by robsdagreat** [comment]
Now that circle ci is not failing , I think you're good to go.

**Review by bahati10 — APPROVED** [review]
Thanks for the fix. Now everything will work as expected

**Review by kirengamartial — CHANGES_REQUESTED** [review]
resolving conflicts

**Review by kirengamartial — APPROVED** [review]

**Pull request merged**
