### PR TITLE
Delete item from collection

### PR DESCRIPTION
**Pull request by Ishimwe7**
### What does this PR do?
This PR implements the functionality to delete a product from the collection in the database.
### Description of Task to be completed?
1. User haver to be logged in and is of type 'seller'
2. The Seller deleting the product have to be the owner of it(ie. product.userId equals to Id of logged-in user)
3. When no product found error 404(NOT FOUND will be thrown)
4. When trying to delete product yet you are not a seller also error will be thrown
### How should this be manually tested?
1. Register as a seller
2. Verify your account
3. Login with valid credentials
4. Try adding product
5. Finally try deleting added product
### What are the relevant pivotal tracker stories
https://www.pivotaltracker.com/story/show/187570876

### CODE REVIEW

**Review by rodriguecyber — COMMENTED** [review]
i see you code looks good

**Review by robsdagreat — APPROVED** [review]

**Review by kirengamartial — CHANGES_REQUESTED** [review]
solve conflicts in those files

**Review by Balinda21 — CHANGES_REQUESTED** [review]
Hello @Ishimwe7  I've reviewed your pull request, and it looks like there are some conflicts that need to be addressed. Thanks!

**Comment by Ishimwe7** [comment]
> Hello @Ishimwe7 I've reviewed your pull request, and it looks like there are some conflicts that need to be addressed. Thanks!

I'll resolve them soon

**Comment by Ishimwe7** [comment]
> solve conflicts in those files

done !

**Review by DeliceLydia — APPROVED** [review]
Well done Pacifique

**Pull request merged**
