### PR TITLE
#187570866 Implement Google login functionality

### PR DESCRIPTION
**Pull request by kirengamartial**
### What does this PR do?
This PR implements the Google login functionality for the application.

### Description of Task to be completed?

- Integrate Google OAuth 2.0 for user authentication.
- Update the authentication flow to include Google sign-in.
- Ensure proper handling of login success and failure scenarios.
- Add necessary configurations and environment variables for Google login.

### Any background context you want to provide?
Google OAuth 2.0 is used to provide a secure and seamless authentication experience for users. This integration will enhance the login process and offer an alternative to traditional username/password authentication.

### What are the relevant pivotal tracker stories
#187570866 : As a user, I can log in to the app via Google.

### CODE REVIEW

**Review by Balinda21 — APPROVED** [review]
looks good. It's clear and thorough

**Review by Ishimwe7 — COMMENTED** [review]
Good job @kirengamartial your codes looks good, consider highlighted section

**Review by derrick-nuby — APPROVED** [review]
Good work! You might consider storing the name of the user in the token so that we can use it later; for example in shopping routes. otherwise good work

**Comment by kirengamartial** [comment]
> Good work! You might consider storing the name of the user in the token so that we can use it later; for example in shopping routes. otherwise good work

it's done

**Review by bahati10 — APPROVED** [review]

**Comment by robsdagreat** [comment]
Nice work !

**Review by robsdagreat — APPROVED** [review]

**Review by DeliceLydia — APPROVED** [review]

**Pull request merged**
