### PR TITLE
forget password and password reset with email verification completed

### PR DESCRIPTION
**Pull request by derrick-nuby**
### What does this PR do?
Adds functionality for password reset and verification through email, including generating and verifying JWT tokens, and hashing new passwords.
### Description of Task to be completed?
* Implement forgotPassword method to send a password reset email with a verification link.
* Implement resetPassword method to verify the token and update the user's password.
* Add getUserByFields method to fetch a user by multiple fields.
* Handle various error cases and provide appropriate responses.
### How should this be manually tested?
* Send a POST request to /forgot with email and phone in the body.
* Check the received email for a password reset link.
* Send a get request to /reset with the token in the querry paramenter and new password in the body.

### API Endpoints

- `POST /forgot`
  - Description: Sends a password reset email with a verification link.
  - Note that a user must be verified to initiate the reset password action
  - Body: 
    ```json
    {
      "email": "user@example.com"
    }
    ```

- `POST /reset?token=VALUE-OF-TOKEN`
  - Description: Verifies the token and updates the user's password.
  - Query Params: 
    - `token`: The JWT token sent
  - Body:
    ```json
    {
      "email": "YourNewPassw0Rd1Here"
    }
    ```

### What are the relevant pivotal tracker stories

#187570868

### CODE REVIEW

**Review by robsdagreat — APPROVED** [review]
Well done Derrick!

**Review by Balinda21 — APPROVED** [review]
I reviewed the changes in this pull request, the code is clean and organized, making it easy to follow.

**Review by kirengamartial — COMMENTED** [review]
resolve conflict

**Review by DeliceLydia — APPROVED** [review]
Good job Derrick

**Pull request merged**
